### ISSUE TITLE
[Whitelist] Murder 4

### ISSUE THREAD

**Issue by chilledge** [emmVRC/emmVRC-Risky-Function-Request#65] opened 2021-07-13 00:05 UTC
Emmvrc can be useful for murder 4 because there are some things that are hard to get around like doors keep getting locked or items disappearing, and emmvrc can help that.

**Comment by rakosi2** [comment] 2021-07-13 00:08
duplicate of #41 and #44 also Murder 4 has teleport detection and will just respawn you if you teleport/fly

**Closed by rakosi2** 2021-07-13 00:08 UTC
