### ISSUE TITLE
(WHITELIST) Murder 4

### ISSUE THREAD

**Issue by l3LUl3oy** [emmVRC/emmVRC-Risky-Function-Request#96] opened 2022-01-05 00:22 UTC
I just want to use it with my friends in friends or friends+. I hope that is a reasonable offer

**Comment by BLANKE1** [comment] 2022-01-05 00:28
this is to request a world globally to be whitelisted, not just yourself. Saying this is essentially just a pinky promise and cannot be properly moderated. Just don't look to cheat in game worlds and ruin experiences for others.

**Comment by rakosi2** [comment] 2022-01-05 00:31
Duplicate of #41 #44 #65 #91 and #93

**Closed by rakosi2** 2022-01-05 00:31 UTC
