### ISSUE TITLE
risky funtion

### ISSUE THREAD

**Issue by Bot16257** [emmVRC/emmVRC-Risky-Function-Request#95] opened 2022-01-02 04:56 UTC
The risky funtion doesn't work for me

**Comment by rakosi2** [comment] 2022-01-02 04:58
Duplicate of #94

**Comment by BLANKE1** [comment] 2022-01-02 04:58
Please stop opening random tickets, use discord

**Closed by rakosi2** 2022-01-02 04:58 UTC
Labels: invalid

**Comment by Bot16257** [comment] 2022-01-02 05:11
im so sorry
