### ISSUE TITLE
whitelist-MURDER MYSTERY 4

### ISSUE THREAD

**Issue by gorrillaman1234567** [emmVRC/emmVRC-Risky-Function-Request#93] opened 2021-12-31 22:26 UTC
WELL ONLY FOR PRIVATE OR FRIENDS+ AND FRIENDS LOBBY HOPE THATS REASONABLE ALSO SORRY FOR CAPS

**Comment by BLANKE1** [comment] 2021-12-31 22:28
That still can be abused for things like party nights, also risky functions will stay in effect no matter what instance type.

**Comment by rakosi2** [comment] 2021-12-31 22:29
Duplicate of #41 #44 #65 and #91

**Closed by rakosi2** 2021-12-31 22:29 UTC
