### ISSUE TITLE
[whitelist] Winter Company

### ISSUE THREAD

**Issue by IrisUwU** [emmVRC/emmVRC-Risky-Function-Request#100] opened 2022-01-21 20:56 UTC
It has the game tag preventing risky functions, it has the game tag because there is a pool table. Having risky functions wouldn't give an unfair advantage to the pool table. There are no private rooms or room locks.

Winter Company by Lucifer MStar
World ID: wrld_f8474f94-684c-47be-84fd-a7ce90a1b5ce
![riskyfuncreq](https://user-images.githubusercontent.com/96803124/150598995-8bdb9121-3f83-4bc2-9181-ea628286e24e.jpg)

**Comment by rakosi2** [comment] 2022-01-23 07:40
Duplicate of #87

**Closed by rakosi2** 2022-01-23 07:40 UTC
