### ISSUE TITLE
Among Us

### ISSUE THREAD

**Issue by IntensePlum123** [emmVRC/emmVRC-Risky-Function-Request#25] opened 2021-01-07 01:22 UTC
Hello, the reason i want to be able to have risky functions in the game world "Among us" is for the fact that my friends at I are looking forward to being able to use our clients in gameso we can have fun doing speed rounds. this will not be used to harrass others.

**Comment by rakosi2** [comment] 2021-01-07 01:24
You may not abuse it however many others will and among us will not be whitelisted. duplicate of #21

**Closed** 2021-01-07 01:33 UTC
